#################################################
# Setup Kubernetes
#################################################
---
- hosts: all
  become: true
  # vars_files:
  #   - vars/default.yml

  tasks:
    - name: Install required system packages for docker
      apt: 
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common 
        state: latest
        update_cache: yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch=arm64] https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: Update apt and install docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
        state: latest

    - name: Create docker group
      group:
        name: docker

    - name: Add user to docker group
      user: 
        name: "{{ ansible_ssh_user }}"
        groups: 
          - docker

    - name: Enable service docker
      systemd:
        name: docker
        enabled: yes
    
    - name: Configure Docker
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "100m"
            },
            "storage-driver": "overlay2"
          }
    
    - name: Reboot
      reboot: {}

    - name: Docker info
      shell: docker info
